### ISSUE TITLE
_id usage

### ISSUE THREAD

**Issue by sgueniot** [BoD/android-contentprovider-generator#79]
hello, 
currently, _id can't be setted and used as normal field, and foreign keys always reference the _id column.
In most apps, an idea is sent by a server, and we have to manage two different ids, and put in database is not easy :
insert object
query object to get _ids
insert subObject.
Instead of just use an applyBatch.

I feel that all limitations are added by contentprovidergenerator to preserve misuse, but its use as a normal fields (ObjectContentValues, ObjectSelection...) could be useful in some cases.

did I miss something ?

thanks

**Comment by BoD** [comment]
I'm not sure I fully understand your question but I would say this:
- the `_id` column is a convention, and even mandatory for instance, when using `CursorAdapter`
- it usually is auto-incremented so it doesn't make sense to be able to set it
- it is a usual thing to add a "server id" column
Please re open if this was not clear ;)

**Comment by codeversed** [comment]
If you have the _id column NOT as auto-incremented, wouldn't it make sense to add a setter? I am revisiting my db structure and I feel like a setter is needed for this. 

If I create, for example, a server id column, then I would manually have to modify the join code since joins and foreign keys can only reference the _id field.
